server:
  host: "0.0.0.0"
  port: 3001
db:
  user: "postgres"
  pass: "mysecretpassword"
  name: "postgres"
  host: "localhost"
  port: 5432
  mode: "disable"
  auto_migrate: true
minio:
  scheme: "https"
  host: "143.198.96.88:9000"
  port: 9001
  accessKey: "AKIAIOSFODNN7EXAMPLE"
  secretKey: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  useSSL: false
  bucket: "onex"