server:
  host: "0.0.0.0"
  port: 3001
db:
  user: "doadmin"
  pass: "rJS7PG5vtTvcbZhk"
  name: "texert_db"
  host: "db-postgresql-ams3-54442-do-user-10520545-0.b.db.ondigitalocean.com"
  port: 25060
  mode: "require"
  auto_migrate: false
minio:
  scheme: "https"
  host: "164.92.217.224:9000"
  port: 9001
  accessKey: "LbBdppKYysQ6JEjj"
  secretKey: "faGwrStMQawHSbtLkdfVEDQQg4nU4MhB"
  useSSL: false
  bucket: "texert"
token:
  ttl: 3600