server:
  host: "0.0.0.0"
  port: 3001
db:
  user: "doadmin"
  pass: "yFgpeO9FbRLuHeFn"
  name: "onex"
  host: "db-postgresql-sfo3-23644-do-user-10147817-0.b.db.ondigitalocean.com"
  port: 25060
  mode: "require"
  auto_migrate: false
minio:
  scheme: "https"
  host: "143.198.96.88:9000"
  port: 9001
  accessKey: "AKIAIOSFODNN7EXAMPLE"
  secretKey: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  useSSL: false
  bucket: "onex"
token:
  ttl: 6000